---
- name: Delete archive jobs that are in complete state
  hosts: localhost
  vars:
    namespace: efg-dma-performance
  tasks:
    - name: Get cluster information
      kubernetes.core.k8s_info:
        kind: Namespace
      register: cluster_info

    - name: Show cluster info
      debug:
        var: cluster_info

    - name: Gather Kubernetes pod facts
      k8s_info:
        kind: pod
        namespace: "{{ namespace }}"
      register: pod_facts
      
    - name: Filter and display pods that are in 'Complete' state
      debug:
        msg: "{{ item.metadata.name }}"
      loop: "{{ pod_facts.resources }}"
      when: "'Succeeded' in item.status.phase"
     
