---
- name: Delete archive jobs that are in complete state
  hosts: localhost
  vars:
    namespace: efg-dma-performance
  tasks:
    - name: Get cluster information
      kubernetes.core.k8s_info:
        kind: Namespace
      register: cluster_info

    - name: Show cluster info
      debug:
        var: cluster_info

    - name: List all pods in the OpenShift project (namespace)
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ namespace }}"
      when: item.status.succeeded is defined and item.status.succeeded == 1
      register: pod_info

    - name: Dump the pod info
      debug:
        msg: "{{ pod_info }}"
