---
- name: List Pods in OpenShift
  hosts: localhost
  vars:
    namespace: efg-dma-performance
  tasks:
    - name: Get cluster information
      kubernetes.core.k8s_info:
        kind: Namespace
      register: cluster_info

    - name: Show cluster info
      debug:
        var: cluster_info

    - name: List all pods in the OpenShift project (namespace)
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ namespace }}"
      register: pod_facts

    - name: Delete archieve-job pods that in complete state
      kubernetes.core.k8s:
        name: "{{ item.metadata.name }}"
        namespace: "{{ namespace }}"
        kind: Job
        state: absent
      loop: "{{ job_info.resources }}"
      when: item.status.succeeded is defined and item.status.succeeded == 1
      loop: "{{ pod_facts.resources }}"
