---
- name: Delete archive jobs that are in complete state
  hosts: localhost
  vars:
    namespace: efg-dma-performance
  tasks:
    - name: Get cluster information
      kubernetes.core.k8s_info:
        kind: Namespace
      register: cluster_info

    - name: Show cluster info
      debug:
        var: cluster_info

    - name: Gather Kubernetes pod facts
      k8s_info:
        kind: pod
        namespace: "{{ namespace }}"
      register: pod_facts

    - name: Delete the pods that are in 'Succeeded' state
      kubernetes.core.k8s:
        kind: Pod
        name: "{{ item.metadata.name }}"
        namespace: "{{ namespace }}"
        state: absent
      loop: "{{ pod_facts.resources }}"
      when: "'Succeeded' in item.status.phase"
      register: deleted_pods

    - name: Show deleted pod names
      debug:
        msg: "Deleted pod: {{ item.item }}"
      loop: "{{ deleted_pods.results }}"
      when: deleted_pods.results | length > 0
