---
- name: simple playbook on windows server
  hosts: all
  become: yes
  tasks:
    - name: Install IIS (Web-Server only) and MSMQ-server
      win_feature:
        name: " {{item}} "
        include_sub_features: true
        include_management_tools: true
        state: present
        restart: yes
      loop:
        - Web-Server
        - MSMQ-Server  
      register: win_feature
      
    - name: Reboot if installing Web-Server or MSMQ-Server feature requires it
      ansible.windows.win_reboot:
      when: 
        - win_feature.results | selectattr('reboot_required', 'equalto', true) | length > 0
  
    - name: Ensure IIS, MSMQ services are running
      win_service:
        name: " {{item}} "
        state: started
        start_mode: auto
      loop:
        -  W3SVC
