---
- name: simple playbook on windows server
  hosts: all
  tasks:
    - name: Install IIS (Web-Server only) and MSMQ-server
      win_feature:
        name: " {{item}} "
        state: present
        restart: yes
      loop:
        - Web-Server
        - MSMQ

    - name: Ensure IIS, MSMQ services are running
      win_service:
        name: " {{item}} "
        state: started
        start_mode: auto
      loop:
        - Web-Server
        - MSMQ
