---
- name: simple playbook on windows server
  hosts: all
  tasks:
    - name: Install IIS (Web-Server only) and MSMQ
      ansible.windows.win_feature:
        name: " {{item}} "
        state: present
      loop:
        - web-server
        - MSMQ-Server
